### PR TITLE
refactor `toMatchSpecificSnapshot`

### PR DESCRIPTION
**Pull request by zvictor**
I was facing performance issues with my tests (the process would hang forever) and I refactored the code and also updated dependencies, on an attempt to find ways to make better use of memory.

### CODE REVIEW

**Comment by zvictor** [comment]
never mind, I found some issues on it.
I am closing it for now.

**Comment by igor-dv** [comment]
Oh.. Maybe you can share what are the issues you have?

**Comment by zvictor** [comment]
Sure! the problem is that with my changes the first story is saved in a different way compared to the rest.

The first one is stored in the global snapshots file, while the rest are saved in their specific/independent files.

**Comment by igor-dv** [comment]
I'll take a look tomorrow on it as well. What are the performance issues? Something related to cloning?

**Comment by zvictor** [comment]
I couldn't be sure what the cause was, but I suspect it was something going on in the saving process. It went away after I updated my local node from `v8.7.0` to `v8.9.3`, so the problem was probably not in this package.

Nevertheless, I decided to create this PR as I consider that the work I had in progress is more performant (as it doesn't make a new copy of the state for every call) and more readable (as it makes use of the `expect` api instead of wrapping the call with the state).

I am sorry if I haven't made the purpose of this PR clear from the beginning. I should have spent more time explaining my goals with this PR when I created it.

**Pull request closed without merging**
